#! /usr/bin/env python

top = '..'
out = 'build'

children = [ 'lib1'
           , 'lib2'
           , 'lib3'
           , 'exe' ]

def configure(ctx):
    ctx.recurse(children)

def build(ctx):
    ctx.recurse(children)

def install(ctx):
    ctx.recurse(children)

