#! /usr/bin/env python

top = '../..'
out = '%s/build' % top

def configure(ctx):
    ctx.load('cabal')

def build(ctx):
    ctx(source = 'lib1.cabal',
        register = True,
        depends_on = [] )
